In [15]:
import pandas as pd

data = pd.concat([pd.read_csv('SDOT_{0}_Traffic_Flow_Counts.csv'.format(year)) for year in range(2007, 2015)])

data

,AAWDT,ADJUSTMENT,AWDT,COMPKEY,DOWNTOWN,FLOWMAP,FLOW_COUNT,GEOBASID,HPMS,HPMS_FLOW_,...,STUDY_ID,STUDY_MAX8,STUDY_PMPK,Shape,Shape_Length,TITLE,YEAR,YEAR_,lat,lon
0,88000.0,NaN,NaN,1270,N,NaN,Y,520040.0,NaN,NaN,...,NaN,NaN,NaN,NaN,6772.179899,NaN,2007.0,NaN,47.548271,-122.334309
1,85100.0,NaN,NaN,13330,N,NaN,Y,102580040.0,NaN,NaN,...,NaN,NaN,NaN,NaN,4775.864940,NaN,2007.0,NaN,47.571506,-122.339234
2,58700.0,NaN,NaN,12881,N,NaN,Y,97450080.0,NaN,NaN,...,NaN,NaN,NaN,NaN,5993.165041,NaN,2007.0,NaN,47.514016,-122.328192
3,57203.0,NaN,NaN,11902,N,NaN,Y,86850010.0,NaN,NaN,...,NaN,NaN,NaN,NaN,1362.068921,NaN,2007.0,NaN,47.645264,-122.304617
4,48000.0,NaN,NaN,10218,N,NaN,Y,65600100.0,NaN,NaN,...,NaN,NaN,NaN,NaN,7015.664707,NaN,2007.0,NaN,47.618618,-122.358478
5,46000.0,NaN,NaN,11911,N,NaN,Y,86950030.0,NaN,NaN,...,NaN,NaN,NaN,NaN,3751.799471,NaN,2007.0,NaN,47.648997,-122.304591
6,44300.0,NaN,NaN,13333,N,NaN,Y,102580290.0,NaN,NaN,...,NaN,NaN,NaN,NaN,7828.178811,NaN,2007.0,NaN,47.571208,-122.358479
7,43300.0,NaN,NaN,2188,N,NaN,Y,5750060.0,NaN,NaN,...,NaN,NaN,NaN,NaN,7640.755892,NaN,2007.0,NaN,47.633499,-122.376195
8,40000.0,NaN,NaN,8957,N,NaN,Y,52500700.0,NaN,NaN,...,NaN,NaN,NaN,NaN,13101.596030,NaN,2007.0,NaN,47.651351,-122.347314
9,39700.0,NaN,NaN,490543,N,NaN,Y,97810020.0,NaN,NaN,...,NaN,NaN,NaN,NaN,6145.389649,NaN,2007.0,NaN,47.534200,-122.332165
10,39600.0,NaN,NaN,19710,N,NaN,Y,156300030.0,NaN,NaN,...,NaN,NaN,NaN,NaN,4139.989004,NaN,2007.0,NaN,47.571578,-122.328989
11,38900.0,NaN,NaN,11166,N,NaN,Y,80150280.0,NaN,NaN,...,NaN,NaN,NaN,NaN,2944.274922,NaN,2007.0,NaN,47.704199,-122.301612
12,38200.0,NaN,NaN,11775,N,NaN,Y,86150160.0,NaN,NaN,...,NaN,NaN,NaN,NaN,1988.338548,NaN,2007.0,NaN,47.624550,-122.342350
13,38000.0,NaN,NaN,12364,N,NaN,Y,93450260.0,NaN,NaN,...,NaN,NaN,NaN,NaN,5670.934775,NaN,2007.0,NaN,47.592163,-122.308690
14,37900.0,NaN,NaN,8988,N,NaN,Y,52501010.0,NaN,NaN,...,NaN,NaN,NaN,NaN,8438.973687,NaN,2007.0,NaN,47.686942,-122.344503
15,36405.0,NaN,NaN,11159,N,NaN,Y,80150170.0,NaN,NaN,...,NaN,NaN,NaN,NaN,8008.679500,NaN,2007.0,NaN,47.685366,-122.315017
16,36300.0,NaN,NaN,11190,N,NaN,Y,80150420.0,NaN,NaN,...,NaN,NaN,NaN,NaN,8237.156889,NaN,2007.0,NaN,47.712044,-122.299512
17,36300.0,NaN,NaN,9001,N,NaN,Y,52501190.0,NaN,NaN,...,NaN,NaN,NaN,NaN,8773.643829,NaN,2007.0,NaN,47.710077,-122.344777
18,35200.0,NaN,NaN,11055,Y,NaN,Y,78850080.0,NaN,NaN,...,NaN,NaN,NaN,NaN,1288.213151,NaN,2007.0,NaN,47.604625,-122.326970
19,35200.0,NaN,NaN,16847,N,NaN,Y,132850100.0,NaN,NaN,...,NaN,NaN,NaN,NaN,2520.909797,NaN,2007.0,NaN,47.661328,-122.322160
20,34700.0,NaN,NaN,12368,N,NaN,Y,93450300.0,NaN,NaN,...,NaN,NaN,NaN,NaN,5857.808120,NaN,2007.0,NaN,47.578350,-122.298151
21,33600.0,NaN,NaN,20848,N,NaN,Y,165650100.0,NaN,NaN,...,NaN,NaN,NaN,NaN,3586.219536,NaN,2007.0,NaN,47.543202,-122.333994
22,33077.0,NaN,NaN,10000,B,NaN,Y,63450045.0,NaN,NaN,...,NaN,NaN,NaN,NaN,1115.205643,NaN,2007.0,NaN,47.618592,-122.352839
23,32900.0,NaN,NaN,2117,N,NaN,Y,5600260.0,NaN,NaN,...,NaN,NaN,NaN,NaN,8045.819617,NaN,2007.0,NaN,47.668667,-122.376214
24,32600.0,NaN,NaN,10015,B,NaN,Y,63450200.0,NaN,NaN,...,NaN,NaN,NaN,NaN,1746.450453,NaN,2007.0,NaN,47.618550,-122.342402
25,31595.0,NaN,NaN,13189,N,NaN,Y,101100010.0,NaN,NaN,...,NaN,NaN,NaN,NaN,2568.736714,NaN,2007.0,NaN,47.651733,-122.321152
26,31100.0,NaN,NaN,18013,N,NaN,Y,139300040.0,NaN,NaN,...,NaN,NaN,NaN,NaN,2973.231830,NaN,2007.0,NaN,47.708637,-122.329928
27,31000.0,NaN,NaN,288753,N,NaN,Y,132850275.0,NaN,NaN,...,NaN,NaN,NaN,NaN,2427.191584,NaN,2007.0,NaN,47.658982,-122.301139
28,30500.0,NaN,NaN,16680,N,NaN,Y,131450030.0,NaN,NaN,...,NaN,NaN,NaN,NaN,7977.188508,NaN,2007.0,NaN,47.734064,-122.324847
29,30300.0,NaN,NaN,10940,N,NaN,Y,73600060.0,NaN,NaN,...,NaN,NaN,NaN,NaN,7786.445631,NaN,2007.0,NaN,47.690609,-122.376806
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
283,6200.0,NaN,NaN,12042,Y,NaN,NaN,89500020.0,Y,NaN,...,NaN,NaN,NaN,"(47.61218154000005, -122.33854264999997)",656.269362,NaN,2014.0,NaN,NaN,NaN
284,6000.0,NaN,NaN,13531,Y,NaN,Y,NaN,NaN,NaN,...,NaN,NaN,NaN,"(47.61330060900008, -122.33743123399995)",1931.624536,NaN,2014.0,NaN,NaN,NaN
285,5700.0,NaN,NaN,11941,N,NaN,Y,87750010.0,Y,NaN,...,NaN,NaN,NaN,"(47.522322333000034, -122.33484135399999)",2781.794818,NaN,2014.0,NaN,NaN,NaN
286,5200.0,NaN,NaN,21861,N,NaN,Y,174000400.0,NaN,NaN,...,NaN,NaN,NaN,"(47.52317298100007, -122.39298987199999)",304.679594,NaN,2014.0,NaN,NaN,NaN
287,5100.0,NaN,NaN,1113,N,NaN,Y,200640.0,NaN,NaN,...,NaN,NaN,NaN,"(47.72316551600005, -122.32891834799995)",3986.725488,NaN,2014.0,NaN,NaN,NaN
288,4900.0,NaN,NaN,8279,Y,NaN,Y,47850140.0,Y,NaN,...,NaN,NaN,NaN,"(47.60794452500005, -122.32847075299998)",3919.718775,NaN,2014.0,NaN,NaN,NaN
289,4800.0,NaN,NaN,5324,N,NaN,Y,26200100.0,NaN,NaN,...,NaN,NaN,NaN,"(47.63955597900008, -122.40100005599999)",7204.640182,NaN,2014.0,NaN,NaN,NaN
290,4800.0,NaN,NaN,2349,N,NaN,Y,6950380.0,NaN,NaN,...,NaN,NaN,NaN,"(47.533680428000025, -122.35503244799997)",5953.083780,NaN,2014.0,NaN,NaN,NaN
291,4800.0,NaN,NaN,4828,N,NaN,Y,22750030.0,NaN,NaN,...,NaN,NaN,NaN,"(47.59912512400007, -122.29258593199995)",8590.215932,NaN,2014.0,NaN,NaN,NaN
292,4700.0,NaN,NaN,5001,N,NaN,Y,23850280.0,NaN,NaN,...,NaN,NaN,NaN,"(47.66753995500005, -122.39831360899996)",8343.257110,NaN,2014.0,NaN,NaN,NaN
293,4000.0,NaN,NaN,9093,N,NaN,Y,53850050.0,NaN,NaN,...,NaN,NaN,NaN,"(47.578355919000046, -122.41328134599996)",17360.705430,NaN,2014.0,NaN,NaN,NaN
294,4000.0,NaN,NaN,8526,Y,NaN,NaN,48900200.0,Y,NaN,...,NaN,NaN,NaN,"(47.61715418400007, -122.33703594599996)",441.973229,NaN,2014.0,NaN,NaN,NaN
295,3900.0,NaN,NaN,7340,N,NaN,Y,38950700.0,NaN,NaN,...,NaN,NaN,NaN,"(47.72311933700007, -122.32356466599998)",3988.297273,NaN,2014.0,NaN,NaN,NaN
296,3800.0,NaN,NaN,11752,N,NaN,Y,86200680.0,NaN,NaN,...,NaN,NaN,NaN,"(47.72320788800005, -122.33418382699995)",3986.473178,NaN,2014.0,NaN,NaN,NaN
297,3700.0,NaN,NaN,8164,Y,NaN,Y,47050150.0,NaN,NaN,...,NaN,NaN,NaN,"(47.61428794700004, -122.33615476899996)",2363.704067,NaN,2014.0,NaN,NaN,NaN
298,3700.0,NaN,NaN,4248,N,NaN,Y,19300260.0,NaN,NaN,...,NaN,NaN,NaN,"(47.632304341000065, -122.39300801799999)",7612.385252,NaN,2014.0,NaN,NaN,NaN
299,3200.0,NaN,NaN,12762,N,NaN,Y,95950080.0,NaN,NaN,...,NaN,NaN,NaN,"(47.66867869200007, -122.38757648699999)",16934.406660,NaN,2014.0,NaN,NaN,NaN
300,3000.0,NaN,NaN,490099,R,NaN,Y,75650010.0,NaN,NaN,...,NaN,NaN,NaN,"(47.604891251000026, -122.32926248999996)",225.508948,NaN,2014.0,NaN,NaN,NaN
301,2700.0,NaN,NaN,15280,N,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,"(47.73413889100004, -122.33431797199995)",1331.039680,NaN,2014.0,NaN,NaN,NaN
302,2000.0,NaN,NaN,8469,N,NaN,Y,48050420.0,NaN,NaN,...,NaN,NaN,NaN,"(47.52647326400006, -122.32558706499998)",3436.949711,NaN,2014.0,NaN,NaN,NaN
303,1100.0,NaN,NaN,490100,R,NaN,Y,75750010.0,NaN,NaN,...,NaN,NaN,NaN,"(47.604891251000026, -122.32926248999996)",327.206009,NaN,2014.0,NaN,NaN,NaN
304,NaN,NaN,NaN,11768,N,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,"(47.62458297400008, -122.35670922099996)",3541.093236,NaN,NaN,NaN,NaN,NaN
305,NaN,NaN,NaN,8762,N,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,"(47.59285933500007, -122.33522491899998)",8753.598597,NaN,NaN,NaN,NaN,NaN
306,NaN,NaN,NaN,9664,Y,NaN,NaN,59000060.0,NaN,NaN,...,NaN,NaN,NaN,"(47.604412909000075, -122.32984160499996)",591.914848,NaN,NaN,NaN,NaN,NaN
307,NaN,NaN,NaN,18037,N,NaN,NaN,139450010.0,NaN,NaN,...,NaN,NaN,NaN,"(47.650543276000064, -122.30761623199999)",958.722889,NaN,NaN,NaN,NaN,NaN
308,NaN,NaN,NaN,11054,Y,NaN,NaN,78850060.0,NaN,NaN,...,NaN,NaN,NaN,"(47.60416123500005, -122.32807857799997)",321.540353,NaN,NaN,NaN,NaN,NaN
309,NaN,NaN,NaN,11587,Y,NaN,NaN,83000090.0,NaN,NaN,...,NaN,NaN,NaN,"(47.606552746000034, -122.33179812299994)",642.791244,NaN,NaN,NaN,NaN,NaN
310,NaN,NaN,NaN,8742,N,NaN,NaN,50500170.0,NaN,NaN,...,NaN,NaN,NaN,"(47.58831040300004, -122.33844063699996)",6192.230082,NaN,NaN,NaN,NaN,NaN
311,NaN,NaN,NaN,1274,N,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,"(47.59239917300005, -122.33549223199998)",183.011077,NaN,NaN,NaN,NaN,NaN
312,NaN,NaN,NaN,1271,N,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,"(47.59476091400006, -122.33457725599999)",1938.703863,NaN,NaN,NaN,NaN,NaN

In [10]:
data_2012 = pd.read_csv('SDOT_2012_Traffic_Flow_Counts.csv', 
                        usecols=['GEOBASID','STNAME','YEAR','AAWDT'])

data_2012.head()

      GEOBASID            STNAME    YEAR    AAWDT
0   94250370.0      RENTON AVE S  2012.0   8213.0
1   50000650.0     AIRPORT WAY S  2012.0  11034.0
2  123450090.0         N 65TH ST  2012.0   7916.0
3    9550200.0           2ND AVE  2012.0   9518.0
4   80150420.0  LAKE CITY WAY NE  2012.0  38107.0